# Test against version of node
environment:
  matrix:
    # node.js
    - nodejs_version: "6"

# install script. (run after repo clonong)
install:
  # Get the latest stable version of node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install module
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debigging
  - node --version
  - npm --version
  # run test
  - npm test

# Don't actually build
build: off